### PR TITLE
PR- Initial release - Recipe app

### PR DESCRIPTION
**Pull request by wickathou**
# Recipe app in Rails
The **Recipe app** keeps track of all your recipes, ingredients, and inventory. It will allow you to save ingredients, keep track of what you have, create recipes, and generate a shopping list based on what you have and what you are missing from a recipe. Also, since sharing recipes is an important part of cooking the app should allow you to make them public so anyone can access them.

## Features
- [x] **read public recipes and their ingredients**
- [x] **authentication and authorization**
- [x] **add/delete foods**
- [x] **add/delete recipes**
- [x] **add/edit/delete ingredients**
- [x] **make a recipe private/public**
- [x] **generate shopping list**

## Other details
[Kanban board](https://github.com/users/GhostEsso/projects/6)

### Team
@GhostEsso 
@wickathou 

The output of our App

image

image
Capture d’écran du 2023-11-16 19-35-09
Capture d’écran du 2023-11-16 19-35-22

### CODE REVIEW

**Review by ridwanediallo — CHANGES_REQUESTED** [review]
# Changes Required ♻️
## Hi team, 
AlmostThereReachGIF

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Your PR looks professional. ✔
- Awesome job! All the tests are passing. ✔


## Required Changes ♻️

- [ ] So far, you've done a great job with your project :clap: . However, when we start the project, we cannot access the food page, the recipes page, or any other pages other than the sign up and sign in page. When I try it manually which is even not a good user experience, I get errors. As a result, we cannot test your project at this time to see if everything is working and looking as expected. Please check to see what the problem is and fix it before submitting for a second review. 👌

### Issue demo :point_down: 

[Screencast from 16.11.2023 16:22:33.webm](https://github.com/GhostEsso/ror-recipe-app/assets/89228743/cfd9daf2-541e-4048-8785-a85d3efcca3a)






## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by GhostEsso** [comment]
@ridwanediallo Hello Code Reviewer hope you're doing well! Thanks for reviewing our code... The code is working properly on my side. To access all sections of the page, you need to be a confirmed user. Once confirmed, you'll be able to view all sections within the application. However, on the homepage, you'll only have access to public recipes. I'm going to record my Screen so that you can see what I mean


image

**Comment by GhostEsso** [comment]
@ridwanediallo Here is the recorded video

[Capture vidéo du 2023-11-16 18-44-52.webm](https://github.com/GhostEsso/ror-recipe-app/assets/114746721/a4dfc809-7fdf-4043-b104-dfc8add8d089)

**Comment by ridwanediallo** [comment]
@GhostEsso I am sorry. But after signing up, I did not see the message about the email confirmation. So it did not come to mind about email confirmation. Please check if everything else is working correctly and submit for another review.

**Comment by ridwanediallo** [comment]
And I did not get any confirmation email.

**Comment by GhostEsso** [comment]
@ridwanediallo Thanks, I noticed that since the other project 'blog_App,' the email confirmation sending isn't working. I'm unsure if this is normal or not. Consequently, I confirmed the email manually from the database. What I wanted to know is whether the confirmation email sending is supposed to be functional?

**Comment by ridwanediallo** [comment]
Yes, even if it does not send an email confirmation. If it asks to confirm the email address, we can get a link from the console to confirm the email, even though it's not a good user experience. So ensure that if you decide to keep the email confirmation, it can send the confirmation email; otherwise, the other user cannot visit your project. But I did not get anything prompt to me, so I did not think of that.

**Comment by GhostEsso** [comment]
@ridwanediallo I tried to create user confirmation link

image

**Review by prolajumokeoni — APPROVED** [review]
Hi @GhostEsso and @wickathou 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- App works properly   ✅ 
 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Adding node_module to `.gitignore` this will reduce the volume of node_modules  file pushed to Git 👍🏿 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
